language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
  - "2.7"
  - "3.3"

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - pip install pytest
  - pip install --only-binary=numpy,scipy numpy scipy

before_script:
  - python -V

script:
  - python setup.py install

notifications:
  email: false
