language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: true

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - pip install --only-binary=numpy,scipy numpy scipy
  - sudo apt-get install portaudio19-dev
  - sudo apt-get install libsndfile1-dev

before_script:
  - python -V

script:
  - python setup.py install

notifications:
  email: false
